name: Build CI Image

on:
  push:
    branches: [ main ]
  schedule:
    - cron:

env:
  IMAGE_CI: ghcr.io/${{ github.repository }}/ci

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      docker:
        image: docker:24.0.5-dind
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull existing image
        run: |
          docker pull ${IMAGE_CI}:latest || echo "::set-output name=NEED_BUILD::true"
        id: pull-image

      - name: Build and push if needed
        if: steps.pull-image.outputs.NEED_BUILD == 'true'
        run: |
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --tag ${IMAGE_CI}:latest \
            --file ./.gitlab/Dockerfile-ci .
          docker push ${IMAGE_CI}:latest

      - name: Skip build if not needed
        if: steps.pull-image.outputs.NEED_BUILD != 'true'
        run: echo "Image exists, skipping build"
