FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends jq curl git && \
    apt-get reinstall --assume-yes ca-certificates && \
    update-ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD [ "/bin/bash" ]
