<<<<<<< HEAD
[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stubs-typing"
version = "1.0.0"
=======
stubPath = "venv/tmp-uv-proj-*/src/stubs-for-easysnmp/stubs-typing/"

[project]
name = "tmp-uv-proj"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "wget==3.2",
    "xmodem>=0.4.7",
    "textfsm",
    "typing-extensions>=1.0.0",
    "allure-pytest==2.13.3",
    "pyserial==3.4",
    "requests>=2.32.3",
    "termcolor>=2.4.0",
    "pycryptodome>=3.20.0,<4",
    "setuptools>=69.5.1,<70",
    "projtmp @ git+https://github.com/BreadPetya/tmp-uv-proj.git#subdirectory=projtmp",
]

[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
allure = ["allure-pytest>=2.0.0"]
tests = ["pytest>=7.0"]
docs = ["sphinx>=5.0"]

[dependency-groups]
generate_docs_env = [
    "Sphinx==6.1.3",
    "sphinxcontrib-confluencebuilder==2.0.0",
    "mistune==0.8.4",
    "m2r2==0.3.3.post2",
]

devel_env = ["neovim"]

[tool.uv]
default-groups = [
    "generate_docs_env",
    "devel_env",
]

[tool.setuptools]
packages = ["libtmp", "projtmp"]


[[tool.uv.index]]
name = "PyPI"
url = "https://pypi.org/simple/"



[tool.uv.sources]
#textfsm = { git = "https://github.com/nigredon1991/tmp-uv-proj", subdirectory = "path/to/textfsm" }
#stubs_typing = { git = "projtmp @ git+https://github.com/nigredon1991/tmp-uv-proj.git#subdirectory=projtmp", branch = "master" }

[tool.black]
line-length = 100

[tool.pyright]
include = ["tmp-uv-proj"]
exclude = ["**/__pycache__"]
reportMissingImports = true
reportMissingTypeStubs = true
# reportMissingModuleSource = false
pythonVersion = "3.12"
pythonPlatform = "Linux"

[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.setuptools.package-dir]
libtmp = "tmp-uv-proj/libtmp"
projtmp = "tmp-uv-proj/projtmp"


>>>>>>> 44f19de (Initial commit)
