name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv build
    
    - name: Create virtual environment
      run: python -m venv .venv
    
    - name: Prepare environment
      run: |
        . .venv/bin/activate
        python -m pip install -e .
    
    - name: Fix package paths
      run: |
        . .venv/bin/activate
        # Безопасное редактирование pyproject.toml
        if [ -f pyproject.toml ]; then
          sed -i.bak 's|tmp-uv-proj/libtmp|libtmp|g' pyproject.toml
          sed -i.bak 's|tmp-uv-proj/projtmp|projtmp|g' pyproject.toml
          rm -f pyproject.toml.bak
        fi
    
    - name: Install project
      run: |
        . .venv/bin/activate
        python -m pip install -e .
    
    - name: Run tests
      run: |
        . .venv/bin/activate
        pytest tests/
