name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv uv
    
    - name: Create virtual environment (fallback methods)
      run: |
        # Пробуем создать через uv
        if ! uv venv .venv; then
          echo "uv venv failed, trying virtualenv..."
          python -m virtualenv .venv
        fi
        
        source .venv/bin/activate
        python -V
    
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install -e .
        uv pip install -r requirements.txt
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
