name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: pip install uv
    
    - name: Create and activate virtual environment
      run: |
        uv venv .venv
        source .venv/bin/activate
    
    - name: Fix package structure in pyproject.toml
      run: |
        # Исправляем пути в pyproject.toml
        sed -i 's|tmp-uv-proj/libtmp|libtmp|g' pyproject.toml
        sed -i 's|tmp-uv-proj/projtmp|projtmp|g' pyproject.toml
        cat pyproject.toml  # Для проверки изменений
    
    - name: Install in development mode
      run: |
        source .venv/bin/activate
        uv pip install --upgrade pip
        uv pip install -e .
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
