name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: pip install uv
    
    - name: Create and activate virtual environment
      run: |
        uv venv .venv
        source .venv/bin/activate
    
    - name: Install core dependencies
      run: |
        source .venv/bin/activate
        uv pip install --upgrade pip
        uv pip install "libtmp @ git+https://github.com/BreadPetya/tmp-uv-proj.git#subdirectory=libtmp"
        uv pip install "projtmp @ git+https://github.com/BreadPetya/tmp-uv-proj.git#subdirectory=projtmp"
        uv pip install "tmp-uv-proj @ git+https://github.com/BreadPetya/tmp-uv-proj.git"
        uv pip install -r requirements.txt
    
    - name: Verify installations
      run: |
        source .venv/bin/activate
        python -c "import libtmp, projtmp, tmp_uv_proj; print(f'Imported: {libtmp.__name__}, {projtmp.__name__}, {tmp_uv_proj.__name__}')"
    
    - name: Lint and test
      run: |
        source .venv/bin/activate
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        pytest
