name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install uv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
    
    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -V
    
    - name: Fix package paths
      run: |
        source .venv/bin/activate
        || true который вызывал ошибку
        sed -i 's|tmp-uv-proj/libtmp|libtmp|g' pyproject.toml
        sed -i 's|tmp-uv-proj/projtmp|projtmp|g' pyproject.toml
    
    - name: Install project
      run: |
        source .venv/bin/activate
        uv pip install -e .
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
