name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install uv build wheel
    
    - name: Fix project structure
      run: |
        # Создаем правильную структуру пакета
        mkdir -p src/tmp_uv_proj
        mv libtmp projtmp tmp-uv-proj/* src/tmp_uv_proj/ 2>/dev/null || true
        
        # Исправляем pyproject.toml
        cat << EOF > pyproject.toml
        [build-system]
        requires = ["setuptools>=65.0.0", "wheel"]
        build-backend = "setuptools.build_meta"

        [project]
        name = "tmp-uv-proj"
        version = "0.1.0"
        packages = {find = {}}
        EOF
    
    - name: Build and install
      run: |
        python -m build --wheel
        uv pip install dist/*.whl
    
    - name: Run tests
      run: |
        python -m pytest
